### PR TITLE
feat(poems layout): scroll gradient

### PR DESCRIPTION
**Pull request by d4rekanguok**
This got a bit more elaborated than I expected!

What I learned / re-learned:
- setting `position: relative` on a overflowed container cause its absoluted children to scroll _with_ the scroll content. To fix this I wrapped the scroll container within another div, and have `position: relative` on that div instead.
- Svelte doesn't allow binding scrollY / scrollHeight on element the same way as `window`. I added an inline scroll listener to get those values.
- We have to calculate max scroll manually because scrollHeight includes the height of the element itself

Screen Recording 2021-12-15 at 4 03 40 PM

I haven't tested on mobile yet, but these scrolling styles are currently only being applied on desktop.

### CODE REVIEW

**Comment by andypbrowne** [comment]
@d4rekanguok I added some style 😎 to the scroll-gradient. Will you review and also help me resolve the merge conflicts?

**Comment by d4rekanguok** [comment]
Looks great Andy! I've resolved the merge conflict. `/poems/_layout` definitely needs to be broken up, it's doing a few things now! 

I recently changed my setting to display scrollbars & notice that they jump out quite a bit, should we put in some css to style the scrollbar for completeness' sake?

Screen Shot 2021-12-20 at 1 37 33 PM

**Comment by andypbrowne** [comment]
Yeah, I'll go ahead and style the scroll bar as well. Thanks for pushing for those details!

**Comment by andypbrowne** [comment]
screenshot-scrollbar artifact

Style added to scrollbar. 
1. The CSS works in Chrome and Safari but not Firefox (this is probably ok). 
2. There is a strange white artifact (see screenshot) that shows up at the bottom of the scroll bar and I can't figure out what it is.

**Comment by andypbrowne** [comment]
Added another couple of lines to the global css and the little white box is gone. It was a `::-webkit-scrollbar-corner`. go figure.

**Pull request merged**
